let resumeData = {
  "imagebaseurl":"https://jmgordon1988.github.io/",
  "name": "John Gordon",
  "role": "Full Stack Web Developer",
  "linkedinId":"https://www.linkedin.com/in/john-gordon-26b27768/",
  "roleDescription": "I enjoy working on both front end and back end, as well as learning new languages to find new ways to create things. I love all types of movies, particularly sci-fi and horror",
  "socialLinks":[
      {
        "name":"linkedin",
        "url":"https://www.linkedin.com/in/john-gordon-26b27768/",
        "className":"fa fa-linkedin"
      },
      {
        "name":"github",
        "url":"https://github.com/jmgordon1988 ",
        "className":"fa fa-github"
      },
    ],
  "aboutme":"I have a B.A. in Film and Media Studies, and have recently completed a coding boot camp specializing in Full Stack Web Development in a variety of languages.",
  "email":"jmgordon1988@gmail.com",
  "education":[
    {
      "UniversityName":"University of California, Irvine",
      "specialization":"Film and Media Studies, B.A.",
    },
    {
      "UniversityName":"University of California, Irvine",
      "specialization":"Coding Boot Camp",
      "Achievements": "Awarded Most Awe-Inspiring and Most Creative award for Crazy Talk, a Mad Libs inspired game."
    }
  ],
  // "work":[
  //   {
  //     "CompanyName":"Some Company",
  //     "specialization":"Some specialization",
  //     "MonthOfLeaving":"Jan",
  //     "YearOfLeaving":"2018",
  //     "Achievements":"Some Achievements"
  //   },
  // ],
  "skillsDescription":"Your skills here",
  "skills":[
    {
      "skillname":"HTML5"
    },
    {
      "skillname":"CSS"
    },
    {
      "skillname":"Reactjs"
    },
    {
      "skillname":"Javascript"
    },
    {
      "skillname":"JQuery"
    },
    {
      "skillname":"MongoDB"
    },
    {
      "skillname":"Ajax"
    },
    {
      "skillname":"NodeJS"
    },
    {
      "skillname":"MySQL"
    },
    {
      "skillname":"Express"
    },
    {
      "skillname":"ES6"
    },
  ],
  "portfolio":[
    {
      "name":"Call of Fathoovu",
      "description":"A Multiple Choice Adventure Game, enter any username and password and get started!",
      "imgurl":"images/portfolio/fathoovu.jpg",
      "imghref": "http://call-of-fathoovu.herokuapp.com/"
    },
    {
      "name":"Crazy Talk",
      "description":"A Mad Libs Inspired Word Game",
      "imgurl":"images/portfolio/crazytalk.JPG",
      "imghref": "https://crazytalk-launch-this.herokuapp.com/"
    },
    {
      "name":"Horror Trivia Game",
      "description":"A Horror Trivia game with working timers, gifs after answers, and score tracking at the end.",
      "imgurl":"images/portfolio/horrortrivia.jpeg",
      "imghref": "https://jmgordon1988.github.io/TriviaGame/"
    },
    {
      "name":"Mission Nutrition",
      "description":"A nutrition calculator that adds a gif of the food as well as it's nutritional information totals in the footer, for entertaining meal calculation.",
      "imgurl":"images/portfolio/nutrition.jpg",
      "imghref":"https://creamdreamextremeteam.github.io/MissionNutrition/"
    },
    {
      "name":"Giphy Scraper",
      "description":"A simple scraper that allows you to type a name and present a number of gifs from the search, as well as being able to click buttons generated from your searches to easily go back and display.",
      "imgurl":"images/portfolio/giphy.png",
      "imghref":"https://jmgordon1988.github.io/Giphy/"
    },
    {
      "name":"Psychic Game",
      "description":"A simple psychic letter guessing game, where you attempt to guess the letter generated by the AI.  Letters selected are chosen on screen, as well as total wins and losses.",
      "imgurl":"images/portfolio/psychic.jpg",
      "imghref":"https://jmgordon1988.github.io/Psychic-Game/"
    },
    {
      "name":"Crystal Collector",
      "description":"A simple numbers game, where values for each crystal are randomly generated at the start of each game, and you must add up to another randomly generated number to win!",
      "imgurl":"images/portfolio/crystal.jpg",
      "imghref":"https://jmgordon1988.github.io/unit-4-game/"
    }
  ],
  "testimonials":[
    {
      "description":"I couldn't think of a quote so this is just going to be a placeholder until I can actually give John one.",
      "name":"Anastasia Augustson"
    },
    {
      "description":"He's very punny.",
      "name":"Phor, God of Punder"
    }
  ]
}

export default resumeData
